/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Category`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/testing`; params?: Router.UnknownInputParams; } | { pathname: `/user`; params?: Router.UnknownInputParams; } | { pathname: `/wallet`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signout` | `/signout`; params?: Router.UnknownInputParams; } | { pathname: `${'/(maps)'}/beauty` | `/beauty`; params?: Router.UnknownInputParams; } | { pathname: `${'/(maps)'}/decor` | `/decor`; params?: Router.UnknownInputParams; } | { pathname: `${'/(maps)'}/electronics` | `/electronics`; params?: Router.UnknownInputParams; } | { pathname: `${'/(maps)'}/gifts` | `/gifts`; params?: Router.UnknownInputParams; } | { pathname: `${'/(maps)'}/kids` | `/kids`; params?: Router.UnknownInputParams; } | { pathname: `${'/(maps)'}/premium` | `/premium`; params?: Router.UnknownInputParams; } | { pathname: `${'/(maps)'}/summer` | `/summer`; params?: Router.UnknownInputParams; } | { pathname: `/redux/slice`; params?: Router.UnknownInputParams; } | { pathname: `/redux/store`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/Category`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/testing`; params?: Router.UnknownOutputParams; } | { pathname: `/user`; params?: Router.UnknownOutputParams; } | { pathname: `/wallet`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signout` | `/signout`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(maps)'}/beauty` | `/beauty`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(maps)'}/decor` | `/decor`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(maps)'}/electronics` | `/electronics`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(maps)'}/gifts` | `/gifts`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(maps)'}/kids` | `/kids`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(maps)'}/premium` | `/premium`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(maps)'}/summer` | `/summer`; params?: Router.UnknownOutputParams; } | { pathname: `/redux/slice`; params?: Router.UnknownOutputParams; } | { pathname: `/redux/store`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/Category${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/testing${`?${string}` | `#${string}` | ''}` | `/user${`?${string}` | `#${string}` | ''}` | `/wallet${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signout${`?${string}` | `#${string}` | ''}` | `/signout${`?${string}` | `#${string}` | ''}` | `${'/(maps)'}/beauty${`?${string}` | `#${string}` | ''}` | `/beauty${`?${string}` | `#${string}` | ''}` | `${'/(maps)'}/decor${`?${string}` | `#${string}` | ''}` | `/decor${`?${string}` | `#${string}` | ''}` | `${'/(maps)'}/electronics${`?${string}` | `#${string}` | ''}` | `/electronics${`?${string}` | `#${string}` | ''}` | `${'/(maps)'}/gifts${`?${string}` | `#${string}` | ''}` | `/gifts${`?${string}` | `#${string}` | ''}` | `${'/(maps)'}/kids${`?${string}` | `#${string}` | ''}` | `/kids${`?${string}` | `#${string}` | ''}` | `${'/(maps)'}/premium${`?${string}` | `#${string}` | ''}` | `/premium${`?${string}` | `#${string}` | ''}` | `${'/(maps)'}/summer${`?${string}` | `#${string}` | ''}` | `/summer${`?${string}` | `#${string}` | ''}` | `/redux/slice${`?${string}` | `#${string}` | ''}` | `/redux/store${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Category`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/testing`; params?: Router.UnknownInputParams; } | { pathname: `/user`; params?: Router.UnknownInputParams; } | { pathname: `/wallet`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signout` | `/signout`; params?: Router.UnknownInputParams; } | { pathname: `${'/(maps)'}/beauty` | `/beauty`; params?: Router.UnknownInputParams; } | { pathname: `${'/(maps)'}/decor` | `/decor`; params?: Router.UnknownInputParams; } | { pathname: `${'/(maps)'}/electronics` | `/electronics`; params?: Router.UnknownInputParams; } | { pathname: `${'/(maps)'}/gifts` | `/gifts`; params?: Router.UnknownInputParams; } | { pathname: `${'/(maps)'}/kids` | `/kids`; params?: Router.UnknownInputParams; } | { pathname: `${'/(maps)'}/premium` | `/premium`; params?: Router.UnknownInputParams; } | { pathname: `${'/(maps)'}/summer` | `/summer`; params?: Router.UnknownInputParams; } | { pathname: `/redux/slice`; params?: Router.UnknownInputParams; } | { pathname: `/redux/store`; params?: Router.UnknownInputParams; };
    }
  }
}
